export const staticCountries = [
  {
    id: 1,
    name: "Germany",
    image: "/image/country/Germany.jpg",
    landmark: "Brandenburg Gate",
  },
  {
    id: 2,
    name: "Netherlands",
    image: "/image/country/Netherlands.jpg",
    landmark: "Amsterdam Canal Houses",
  },
  {
    id: 3,
    name: "Belgium",
    image: "/image/country/Belgium.jpg",
    landmark: "Atomium Brussels",
  },
  {
    id: 4,
    name: "France",
    image: "/image/country/France.jpg",
    landmark: "Eiffel Tower",
  },
  {
    id: 5,
    name: "Italy",
    image: "/image/country/Italy.jpg",
    landmark: "Colosseum Rome",
  },
  {
    id: 6,
    name: "Bulgaria",
    image: "/image/country/Bulgaria.jpg",
    landmark: "Sofia Cathedral",
  },
  {
    id: 7,
    name: "Estonia",
    image: "/image/country/Estonia.jpg",
    landmark: "Tallinn Old Town",
  },
  {
    id: 8,
    name: "Hungary",
    image: "/image/country/Hungary.jpg",
    landmark: "Parliament Building",
  },
  {
    id: 9,
    name: "Portugal",
    image: "/image/country/Portugal.jpg",
    landmark: "Pena Palace",
  },
  {
    id: 10,
    name: "Iceland",
    image: "/image/country/Iceland.jpg",
    landmark: "Blue Lagoon",
  },
  {
    id: 11,
    name: "Poland",
    image: "/image/country/Poland.jpg",
    landmark: "Warsaw Old Town",
  },
  {
    id: 12,
    name: "Norway",
    image: "/image/country/Norway.jpg",
    landmark: "Norwegian Fjords",
  },
  {
    id: 13,
    name: "Switzerland",
    image: "/image/country/Switzerland.jpg",
    landmark: "Matterhorn",
  },
  {
    id: 14,
    name: "Spain",
    image: "/image/country/Spain.jpg",
    landmark: "Sagrada Familia",
  },
  {
    id: 15,
    name: "Malta",
    image: "/image/country/Malta.jpg",
    landmark: "Valletta Harbor",
  },
  {
    id: 16,
    name: "Luxembourg",
    image: "/image/country/Luxembourg.jpg",
    landmark: "Grand Ducal Palace",
  },
  {
    id: 17,
    name: "Greece",
    image: "/image/country/Greece.jpg",
    landmark: "Parthenon",
  },
  {
    id: 18,
    name: "Finland",
    image: "/image/country/Finland.jpg",
    landmark: "Helsinki Cathedral",
  },
];
