export const countryCodeMap = {
    "France": "fr",
    "Germany": "de",
    "Italy": "it",
    "Spain": "es",
    "Netherlands": "nl",
    "Belgium": "be",
    "Austria": "at",
    "Greece": "gr",
    "Portugal": "pt",
    "Switzerland": "ch",
    "Norway": "no",
    "Sweden": "se",
    "Denmark": "dk",
    "Finland": "fi",
    "Iceland": "is",
    "Poland": "pl",
    "Czech Republic": "cz",
    "Hungary": "hu",
    "Slovakia": "sk",
    "Slovenia": "si",
    "Estonia": "ee",
    "Latvia": "lv",
    "Lithuania": "lt",
    "Malta": "mt",
    "Luxembourg": "lu",
    "Liechtenstein": "li",
    "United Kingdom": "gb",
};